import 'package:flutter/material.dart';

enum AppTheme { lightTheme, darkTheme }

class AppThemes {
  static final appThemeData = {
    AppTheme.darkTheme: ThemeData(
      colorScheme: const ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xFFFFB5A0),
        onPrimary: Color(0xFF5F1500),
        primaryContainer: Color(0xFF862200),
        onPrimaryContainer: Color(0xFFFFDBD1),
        secondary: Color(0xFFFFB59F),
        onSecondary: Color(0xFF5E1600),
        secondaryContainer: Color(0xFF852300),
        onSecondaryContainer: Color(0xFFFFDBD0),
        tertiary: Color(0xFFFFB59E),
        onTertiary: Color(0xFF5E1700),
        tertiaryContainer: Color(0xFF7F2A0D),
        onTertiaryContainer: Color(0xFFFFDBD0),
        error: Color(0xFFFFB4AB),
        errorContainer: Color(0xFF93000A),
        onError: Color(0xFF690005),
        onErrorContainer: Color(0xFFFFDAD6),
        background: Color(0xFF3F0300),
        onBackground: Color(0xFFFFDAD4),
        surface: Color(0xFF3F0300),
        onSurface: Color(0xFFFFDAD4),
        surfaceVariant: Color(0xFF53433F),
        onSurfaceVariant: Color(0xFFD8C2BC),
        outline: Color(0xFFA08C87),
        onInverseSurface: Color(0xFF3F0300),
        inverseSurface: Color(0xFFFFDAD4),
        inversePrimary: Color(0xFFB02F00),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFFFFB5A0),
        outlineVariant: Color(0xFF53433F),
        scrim: Color(0xFF000000),
      ),
      drawerTheme: const DrawerThemeData(shape: LinearBorder.none),
      // Code to add native ripple for BottomNavigationBar
      // Ref: https://github.com/flutter/flutter/issues/43515#issuecomment-612782673
      splashFactory: InkRipple.splashFactory,
      highlightColor: Colors.transparent,
      splashColor: Colors.red.shade900.withOpacity(0.1),
    ),
    AppTheme.lightTheme: ThemeData(
      colorScheme: const ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFFB02F00),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFFFFDBD1),
        onPrimaryContainer: Color(0xFF3B0900),
        secondary: Color(0xFFAD3306),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFFFDBD0),
        onSecondaryContainer: Color(0xFF3A0A00),
        tertiary: Color(0xFF9F4122),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFFFFDBD0),
        onTertiaryContainer: Color(0xFF3A0B00),
        error: Color(0xFFBA1A1A),
        errorContainer: Color(0xFFFFDAD6),
        onError: Color(0xFFFFFFFF),
        onErrorContainer: Color(0xFF410002),
        background: Color(0xFFFFEDE9),
        onBackground: Color(0xFF3F0300),
        surface: Color(0xFFFFEDE9),
        onSurface: Color(0xFF3F0300),
        surfaceVariant: Color(0xFFF5DED8),
        onSurfaceVariant: Color(0xFF53433F),
        outline: Color(0xFF85736E),
        onInverseSurface: Color(0xFFFFEDE9),
        inverseSurface: Color(0xFF5F150A),
        inversePrimary: Color(0xFFFFB5A0),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFFB02F00),
        outlineVariant: Color(0xFFD8C2BC),
        scrim: Color(0xFF000000),
      ),
      drawerTheme: const DrawerThemeData(shape: LinearBorder.none),
      // Code to add native ripple for BottomNavigationBar
      // Ref: https://github.com/flutter/flutter/issues/43515#issuecomment-612782673
      splashFactory: InkRipple.splashFactory,
      highlightColor: Colors.transparent,
      splashColor: const Color(0xFFFFB5A0).withOpacity(0.2),
    ),
  };
}
